/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package snake;

import java.awt.BorderLayout;
import java.awt.Color;
import surfacegames.GamePanel;
import surfacegames.GameWindow;
import surfacegames.MainWindow;

/**
 *
 * @author jlsuarezdiaz
 */
public class SnakeWindow extends GameWindow{

    /**
     * Creates new form SnakeWindow
     */
    public SnakeWindow() {
        super();
        initComponents();
        snakePanel.setScoreable(scoreboard);
        //setPreferredSize(snakePanel.getDimension());
    }
    
    public SnakeWindow(MainWindow g){
        super(g);
        initComponents();
        snakePanel.setScoreable(scoreboard);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        scoreboard = new scoreboard.Scoreboard(6);
        scoreboard.setHeight(48);
        scoreboard.setForegroundColor(Color.GREEN);
        snakePanel = new snake.SnakePanel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Snake");

        jPanel3.setLayout(new java.awt.BorderLayout());

        scoreboard.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        scoreboard.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        jPanel3.add(scoreboard, java.awt.BorderLayout.PAGE_START);

        snakePanel.setLayout(new java.awt.FlowLayout());
        jPanel3.add(snakePanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private scoreboard.Scoreboard scoreboard;
    private snake.SnakePanel snakePanel;
    // End of variables declaration//GEN-END:variables

    //@Override
    public GamePanel getGamePanel() {
        return this.snakePanel;
    }
}
