/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package surfacegames;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import javax.swing.JDesktopPane;

/**
 *
 * @author jlsuarezdiaz
 */
public class BackgroundDesktop extends JDesktopPane {
    private BufferedImage backgroundImage =  null;
    
    
    
    /**
     * Creates new form BackgroundDesktop
     */
    public BackgroundDesktop() {
        initComponents();
    }
    
    public void setBackgroundImage(BufferedImage img){
        this.backgroundImage = img;
    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        
        try{
            if(backgroundImage != null){
                g.drawImage(backgroundImage, 0, 0, this.getWidth(), this.getHeight(), this);
            }
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
