/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package surfacegames;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.event.ActionListener;
import static java.lang.Math.ceil;
import static utils.Math.mod;

/**
 *
 * @author jlsuarezdiaz
 */
public abstract class GamePanel extends javax.swing.JPanel implements ActionListener{
    
    protected Dimension dim = new Dimension(400,400);
    
    protected Surface surface = Surface.DISK;

    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        initComponents();
        setPreferredSize(dim);
    }
    
    public void setSurface(Surface s){
        this.surface = s;
    }
    
    public Surface getSurface(){
        return this.surface;
    }
    
    public void setDimension(Dimension d){
        this.dim = d;
        setPreferredSize(dim);
    }
    
    public Dimension getDimension(){
        return this.dim;
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        switch(surface){
            //TODO pintar un borde (línea degradada para identificar los bordes en el rectágulo).
        }
    }
    
    
    
    /**
     * Calcula las coordenadas dentro del panel del punto dado, según la superficie.
     * @param p
     * @return Coordenadas equivalentes del punto en el panel, o null si el punto ha sobrepasado el borde de la superficie. 
     */
    public Point getCanonicalCoordinates(Point p){
        int w = dim.width;
        int h = dim.height;
        int x = p.x;
        int y = p.y;
        Point psurf = null;
        
        switch(surface){
            case DISK:
                if(x >= 0 && x <= w && y >= 0 && y <= h)
                    psurf = p;
                break;
            case V_SPHERE:
                //TODO
                /*
                if(y > h || y < 0){ //TODO hacerlo con módulos por si el punto se pasa dos veces la frontera
                    psurf = new Point(mod(w-x,w),mod(h-y,h));
                }
                else{
                    psurf = new Point(mod(x,w),mod(y,h));
                }
                */
                break;
            case H_SPHERE:
                //TODO
                break;
            case V_CYLINDER:
                if(y >= 0 && y <= h){
                    psurf = new Point(mod(x,w),y);
                }
                break;
            case H_CYLINDER:
                if(x >= 0 && x <= w){
                    psurf = new Point(x,mod(y,h));
                }
                break;
            case TORUS:
                psurf = new Point(mod(x,w), mod(y,h));
                break;
              
        }
        
        return psurf;
    }
    
    public boolean isOnBorder(Point p){
        int w = dim.width;
        int h = dim.height;
        int x = p.x;
        int y = p.y;
        
        switch(surface){
            case V_SPHERE:
            case H_SPHERE:
            case TORUS:
                return false;
            case DISK:
                return x==0 || x==w || y==0 || y == h;
            case V_CYLINDER:
                return y==0 || y== h;
            case H_CYLINDER:
                return x==0 || x==w;
        }
        return false;
    }
    
    public boolean isOnOrientationChange(Point p){
        int w = dim.width;
        int h = dim.height;
        int x = p.x;
        int y = p.y;
        switch(surface){
            case DISK:
            case V_CYLINDER:
            case H_CYLINDER:
            case TORUS:
                return false;
            case V_SPHERE:
                //return y >= h || y < 0;
            
        }
        return false;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
