/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puzzle;

import surfacegames.GamePanel;
import surfacegames.GameWindow;
import surfacegames.MainWindow;

/**
 *
 * @author nuria
 */
public class PuzzleWindow extends GameWindow{
    /**
    * Creates new form SnakeWindow
    */
    public PuzzleWindow() {
        super();
        initComponents();
        //setPreferredSize(snakePanel.getDimension());
    }
    
    public PuzzleWindow(MainWindow g){
        super(g);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        puzzlePanel = new puzzle.PuzzlePanel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Puzzle");

        javax.swing.GroupLayout snakePanelLayout = new javax.swing.GroupLayout(puzzlePanel);
        puzzlePanel.setLayout(snakePanelLayout);
        snakePanelLayout.setHorizontalGroup(
            snakePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        snakePanelLayout.setVerticalGroup(
            snakePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        getContentPane().add(puzzlePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private puzzle.PuzzlePanel puzzlePanel;
    // End of variables declaration                   

    //@Override
    public GamePanel getGamePanel() {
        return this.puzzlePanel;
    }
}
