/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minesweeper;

import java.awt.Color;
import surfacegames.GamePanel;
import surfacegames.GameWindow;
import surfacegames.MainWindow;

/**
 *
 * @author jlsuarezdiaz
 */
public class MinesWindow extends GameWindow {

    MainWindow parent;
    
    /**
     * Creates new form MinesWindow2
     */
    public MinesWindow() {
        initComponents();
    }
    
    public MinesWindow(MainWindow g){
        super(g);
        initComponents();
        mineSweeper21.setMinesScore(minesBoard);
        mineSweeper21.setTimeScore(timeBoard);
        mineSweeper21.setTheFace(faceBt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scorePanel = new javax.swing.JPanel();
        minesBoard = new scoreboard.Scoreboard(3);
        faceBt = new javax.swing.JButton();
        timeBoard = new scoreboard.Scoreboard(4);
        mineSweeper21 = new minesweeper.MinesPanel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Buscaminas");

        jPanel1.setLayout(new java.awt.BorderLayout());

        scorePanel.setLayout(new java.awt.BorderLayout());

        minesBoard.setForegroundColor(Color.RED);
        minesBoard.setHeight(24);
        scorePanel.add(minesBoard, java.awt.BorderLayout.LINE_START);

        faceBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minesweeper/media/happy.png"))); // NOI18N
        faceBt.setPreferredSize(new java.awt.Dimension(28, 28));
        scorePanel.add(faceBt, java.awt.BorderLayout.CENTER);

        timeBoard.setForegroundColor(Color.CYAN);
        timeBoard.setHeight(24);
        scorePanel.add(timeBoard, java.awt.BorderLayout.LINE_END);

        jPanel1.add(scorePanel, java.awt.BorderLayout.PAGE_START);

        mineSweeper21.setLayout(new java.awt.BorderLayout());
        jPanel1.add(mineSweeper21, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton faceBt;
    private javax.swing.JPanel jPanel1;
    private minesweeper.MinesPanel mineSweeper21;
    private scoreboard.Scoreboard minesBoard;
    private javax.swing.JPanel scorePanel;
    private scoreboard.Scoreboard timeBoard;
    // End of variables declaration//GEN-END:variables

    @Override
    public GamePanel getGamePanel() {
        return mineSweeper21;
    }
}
