/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minesweeper;

import surfacegames.GamePanel;
import surfacegames.GameWindow;
import surfacegames.MainWindow;

/**
 *
 * @author Javier
 */
public class MinesWindow extends GameWindow {

    /**
     * Creates new form NewJInternalFrame
     */
    public MinesWindow() {
        initComponents();
    }

    public MinesWindow(MainWindow g){
        super(g);
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minesweeper1 = new minesweeper.Minesweeper();

        setClosable(true);
        setIconifiable(true);

        javax.swing.GroupLayout minesweeper1Layout = new javax.swing.GroupLayout(minesweeper1);
        minesweeper1.setLayout(minesweeper1Layout);
        minesweeper1Layout.setHorizontalGroup(
            minesweeper1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );
        minesweeper1Layout.setVerticalGroup(
            minesweeper1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        getContentPane().add(minesweeper1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private minesweeper.Minesweeper minesweeper1;
    // End of variables declaration//GEN-END:variables

   // @Override

    @Override
    public GamePanel getGamePanel() {
        return this.minesweeper1;
    }

}
